### ISSUE TITLE
patch ACPI table

### ISSUE THREAD

**Issue by souhaiebtar** [intruder16/Y510p-OS-X#1]
i saved my DSDT.bin file of my laptop using "Read-Write Everything",
in
 ./Y510p.sh -t "target dir"
is "target dir" is the target of my DSDT.bin file that was previously saved ?

is it correct what i'm saying ?

"target dir" ??

**Comment by intruder16** [comment]
Extremely sorry for late reply. 

The script will only work if the target directory contains *.aml files. Try using clover for extracting DSDT/SSDT's. For other extraction methods, a link is given in the description. Hope it helps.

**Comment by intruder16** [comment]
Hope it helped. Closing it.
